# Generated by Django 4.0 on 2021-12-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=10)),
                ('trainer_id', models.CharField(max_length=5)),
                ('description', models.TextField()),
                ('syllabus', models.FileField(upload_to='')),
            ],
        ),
    ]
