# Generated by Django 4.0 on 2021-12-21 12:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('second_name', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=25)),
                ('course_name', models.CharField(max_length=20)),
                ('course', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('joining_date', models.DateField()),
                ('salary', models.BigIntegerField()),
                ('city', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
                ('contract', models.FileField(upload_to='')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
    ]
