# Generated by Django 4.0 on 2022-01-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_of_event',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_of_event',
            field=models.SmallIntegerField(),
        ),
    ]
