# Generated by Django 4.0 on 2022-01-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_end_of_event_alter_event_start_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_of_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_of_event',
        ),
    ]
