# Generated by Django 4.0 on 2021-12-21 12:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('Nationality', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('class_name', models.CharField(max_length=20)),
                ('nationality_id', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('admission_date', models.DateField()),
                ('academic_year', models.ImageField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('guardians_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('student_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('room', models.CharField(max_length=20)),
            ],
        ),
    ]
