# Generated by Django 4.0 on 2021-12-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Stores first name of student', max_length=15),
        ),
    ]
